services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: cooperfilme
      POSTGRES_USER: cooperfilme
      POSTGRES_PASSWORD: cooperfilme234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cooperfilme -d cooperfilme"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: spring-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/cooperfilme
      SPRING_DATASOURCE_USERNAME: cooperfilme
      SPRING_DATASOURCE_PASSWORD: cooperfilme234
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    restart: always

volumes:
  pgdata: